/*
 * Catroid: An on-device visual programming system for Android devices
 * Copyright (C) 2010-2026 The Catrobat Team
 * (<http://catrobat.org>)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * An additional term exception under section 7 of the GNU Affero
 * General Public License, version 3, is available at
 * http://catrobat.org
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://gnu.org>.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.23.7"
    id 'com.google.devtools.ksp' version '2.0.21-1.0.25' apply true
    id 'checkstyle'
}

repositories {
    mavenLocal()
    maven { url = "https://jitpack.io" }
}

ext {
    appId = 'org.catrobat.catroid'
    appName = '@string/app_name'
    manifestAppName = '@string/app_name'
    manifestAppIcon = '@mipmap/ic_launcher'

    projectVersion = "0.9"
    gdxVersion = "1.13.0"
    mockitoVersion = '5.14.2'
    mockkVersion = "1.14.7"
    espressoVersion = '3.6.1'
    playServicesVersion = '18.1.1'
    cameraXVersion = '1.4.0'
    room_version = "2.6.1"
    coroutines_version = '1.9.0'
    work_manager_version = '2.9.1'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

apply from: 'gradle/code_quality_tasks.gradle'
apply from: 'gradle/release_crowdin_tasks.gradle'
apply from: 'gradle/standalone_apk_tasks.gradle'
apply from: 'gradle/setup_jacoco.gradle'
apply from: 'gradle/emulator.gradle'

if (rootProject.hasProperty('independent')) {
    println "Independent build"
    def today = new Date()
    def independentPackageSuffix = rootProject.hasProperty('independentPackageSuffix')
            ? rootProject.property('independentPackageSuffix')
            : today.format('YYYYMMdd_HHmm')
    appId += '.independent_' + independentPackageSuffix
    appName = rootProject.property('independent') ?: 'Code ' + today.format('MMdd HH:mm')
    manifestAppName = appName
}

ext.getProperty = { property, defaultValue ->
    rootProject.hasProperty(property) ? rootProject.property(property) : defaultValue
}

ext.useAndroidLocales = { ->
    rootProject.hasProperty('useAndroidLocales') ? 'true' : 'false'
}

ext.copyGoogleServicesFile = { flavorName, flavorId ->
    copy {
        from "google-services-template.json"
        rename { "google-services.json" }
        into "src/$flavorName"
        filter { line ->
            line.replaceAll('@appId@', flavorId)
        }
    }
}

def defaultVersionCode = 102
def defaultVersionName = "1.4.1"

android {
    // Força o ecossistema Gradle e Kotlin a compilarem usando o Java 21
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    
    kotlin {
        jvmToolchain(21)
    }

    compileSdk = 35

    namespace = 'org.catrobat.catroid'

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    defaultConfig {
        minSdkVersion 28
        targetSdkVersion 35
        applicationId appId
        testInstrumentationRunner 'org.catrobat.catroid.runner.UiTestApplicationRunner'
        versionCode defaultVersionCode
        versionName defaultVersionName
        println "VersionCode is $versionCode"
        println "VersionName is $versionName"
        manifestPlaceholders += [appName: manifestAppName,
                                 appIcon: manifestAppIcon,
                                 intentFilterScheme: "https",
                                 intentFilterHost: "share.catrob.at",
                                 intentFilterPathPattern: "/.*/project/.*"]

        buildConfigField "String", "GIT_COMMIT_INFO", "\"${getGitCommitInfo()}\""
        buildConfigField "String", "WEB_TEST_URL", "\"" + project.getProperties().get('webTestUrl') + "\""
        buildConfigField "boolean", "WEB_TEST_FLAG", (project.hasProperty('webTestUrl') ? 'true' :
                'false')

        buildConfigField "String", "PROJECT_NAME", "\"No Standalone Project\""
        buildConfigField "String", "START_PROJECT", "\"No Starting Project\""

        buildConfigField "boolean", "USE_ANDROID_LOCALES_FOR_SCREENSHOTS", "false"

        buildConfigField "boolean", "FEATURE_LIST_AS_BASIC_DATATYPE", "false"

        buildConfigField "boolean", "FEATURE_AI_SENSORS_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_APK_GENERATOR_ENABLED", "false"
        buildConfigField "boolean", "FEATURE_ARDUINO_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_CAST_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_EMBROIDERY_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_PLOT_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_LEGO_NXT_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_LEGO_EV3_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_PARROT_AR_DRONE_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_PARROT_JUMPING_SUMO_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_PHIRO_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_MERGE_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_NFC_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_POCKETMUSIC_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_RASPI_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_MQTT_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_SCRATCH_CONVERTER_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_USER_REPORTERS_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_MULTIPLAYER_VARIABLES_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_TESTBRICK_ENABLED", "true"
        buildConfigField "boolean", "FEATURE_AI_ASSIST_ENABLED", "false"
        resValue "string", "FEATURE_EMBROIDERY_PREFERENCES_ENABLED", "false"
        resValue "string", "FEATURE_PHIRO_PREFERENCES_ENABLED", "false"
        resValue "string", "FEATURE_MINDSTORMS_PREFERENCES_ENABLED", "false"
        resValue "string", "FEATURE_AI_PREFERENCES_ENABLED", "false"
        resValue "string", "SNACKBAR_HINTS_ENABLED", "false"
        resValue "string", "DEBUG_MODE", "false"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }


    testOptions {
        unitTests.returnDefaultValues = true
        unitTests.includeAndroidResources = true
        unitTests.all {
            jvmArgs '-Xmx2g'
        }
        animationsDisabled = true
    }

    sourceSets {
        androidTest {
            resources.srcDirs += ['src/androidTest/res', 'src/androidTest/assets']
        }
    }

    packagingOptions {
        jniLibs {
            excludes += ['lib/mips/*', 'lib/armeabi/*']
        }
        resources {
            excludes += ['LICENSE.txt', 'META-INF/LICENSE.md', 'META-INF/INDEX.LIST', 'lib/mips/*', 'lib/armeabi/*']
        }
    }


    signingConfigs {
        signedRelease {
            storeFile file(System.getenv("SIGNING_KEYSTORE") ?: "dummyKeystore")
            storePassword System.getenv("SIGNING_KEY_PASSWORD") ?: ""
            keyAlias System.getenv("SIGNING_KEY_ALIAS") ?: ""
            keyPassword System.getenv("SIGNING_KEY_PASSWORD") ?: ""
        }

        debug {
            storeFile file("external/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        debug {
            buildConfigField "boolean", "USE_ANDROID_LOCALES_FOR_SCREENSHOTS", "false"
        }
    }
}
